# Generated by Django 5.1.3 on 2024-11-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_user_friends_user_followers_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
