# Generated by Django 5.1.3 on 2024-11-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_message_options_remove_userprofile_telephone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
