# Generated by Django 5.1.3 on 2025-01-01 14:16

import base.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_fullname_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='unread_msg_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to=base.helper.user_upload_image_path),
        ),
    ]
